using System.Collections;
using NUnit.Framework;
using Unity.RecordedTesting;
using Unity.RecordedTesting.TestTools;
using UnityEngine.TestTools;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/SolveImageGuess.json"
    /// You can regenerate this file from the Unity Editor Menu: Tools > Automated QA > Generate Recorded Tests
    /// </summary>
    public class RecordedTest_SolveImageGuess : RecordedTestSuite
    {
        [UnitySetUp]
        public IEnumerator Setup()
        {
            UITestSetup.SetupUITests();
            yield return null;
        }
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [RecordedTest("Recordings/SolveImageGuess.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();
            Assert.IsTrue(true);
        }
    }
}
