using System.Collections;
using System.IO;
using NUnit.Framework;
using Unity.RecordedTesting;
using Unity.RecordedTesting.TestTools;
using UnityEngine;
using UnityEngine.TestTools;
using WordHoarder.Utility;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/LoadGame.json"
    /// You can regenerate this file from the Unity Editor Menu: Tools > Automated QA > Generate Recorded Tests
    /// </summary>
    public class RecordedTest_LoadGame : RecordedTestSuite
    {
        [UnitySetUp]
        public IEnumerator SaveSetup()
        {
            var data = Application.dataPath + "/Tests/UI Test Data/DataLoad";
            string path = Application.persistentDataPath + "/" + SaveUtility.SaveFolderName;
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            File.Copy(data, path + "/" + SaveUtility.SaveFileName + "0", true);
            yield return null;
        }
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [RecordedTest("Recordings/LoadGame.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();
            Assert.IsTrue(true);
        }
    }
}
